import {
  Chart,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  Title,
  Tooltip,
  Legend,
  Filler,
  CategoryScale,
} from "chart.js";
import type { MethodFamily, MethodConfig, SeriesPoint, SolverResult } from "./solvers";
import {
  integrateFirstOrder,
  integrateSecondOrder,
  compileScalarExpr,
} from "./solvers";
import {
  METHOD_CATALOG,
  FIRST_ORDER_CATALOG,
  catalogByFamily,
  displayNameFor,
  type MethodCatalogEntry,
} from "./methodCatalog";
import { escapeHtml, formatCoefficients } from "./mathDisplay";
import type { ProblemInputs } from "./aiTutor";
import { mountAiTutorPanel, resetTutorConversation } from "./aiTutorPanel";
import "./style.css";

Chart.register(
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend,
  Filler
);

export interface SelectedMethod {
  family: MethodFamily;
  order?: number;
}

type Step = "choose" | "configure" | "results";

type Session =
  | { mode: "single" }
  | { mode: "compare_pick"; first: SelectedMethod | null }
  | { mode: "compare"; a: SelectedMethod; b: SelectedMethod };

interface PersistedForm {
  t0: string;
  tEnd: string;
  h: string;
  expr: string;
  y0: string;
  u0: string;
  v0: string;
  order: string;
  problemKind: "first" | "second";
}

const DEFAULT_LEDE =
  "Explore numerical methods for initial value problems, compare orders of accuracy, and visualize approximate solutions.";

let step: Step = "choose";
let session: Session = { mode: "single" };
let selected: SelectedMethod | null = null;
let chart: Chart | null = null;
let lastResult: SolverResult | null = null;
let lastCompare: {
  a: SelectedMethod;
  b: SelectedMethod;
  resultA: SolverResult;
  resultB: SolverResult;
} | null = null;
let persisted: PersistedForm | null = null;
let lastProblemInputs: ProblemInputs | null = null;
let comparePickError = "";

const app = document.querySelector<HTMLDivElement>("#app")!;

function catalogEntry(sel: SelectedMethod): MethodCatalogEntry {
  return catalogByFamily(sel.family);
}

function methodLabel(sel: SelectedMethod): string {
  return displayNameFor(sel.family, sel.order);
}

function selectedMeta(): MethodCatalogEntry | null {
  return selected ? catalogEntry(selected) : null;
}

function configFromSelection(sel: SelectedMethod): MethodConfig {
  const cat = catalogEntry(sel);
  const order = cat.hasOrderSelector
    ? Number(sel.order ?? cat.orderDefault ?? 2)
    : undefined;
  return { family: sel.family, order };
}

function persistFromFirstOrderFd(fd: FormData): void {
  persisted = {
    t0: String(fd.get("t0") ?? "0"),
    tEnd: String(fd.get("tEnd") ?? "5"),
    h: String(fd.get("h") ?? "0.05"),
    expr: String(fd.get("expr") ?? "-y"),
    y0: String(fd.get("y0") ?? "1"),
    u0: persisted?.u0 ?? "1",
    v0: persisted?.v0 ?? "0",
    order: String(fd.get("order") ?? persisted?.order ?? "2"),
    problemKind: "first",
  };
}

function persistFromSecondOrderFd(fd: FormData): void {
  persisted = {
    t0: String(fd.get("t0") ?? "0"),
    tEnd: String(fd.get("tEnd") ?? "5"),
    h: String(fd.get("h") ?? "0.05"),
    expr: String(fd.get("expr") ?? "-u"),
    y0: persisted?.y0 ?? "1",
    u0: String(fd.get("u0") ?? "1"),
    v0: String(fd.get("v0") ?? "0"),
    order: persisted?.order ?? "2",
    problemKind: "second",
  };
}

function readPersistedFromFormEl(form: HTMLFormElement): void {
  const fd = new FormData(form);
  if (fd.has("y0")) persistFromFirstOrderFd(fd);
  else persistFromSecondOrderFd(fd);
}

function orderFieldHtml(cat: MethodCatalogEntry): string {
  if (!cat.hasOrderSelector) return "";
  const min = cat.orderMin ?? 1;
  const max = cat.orderMax ?? 8;
  const val = persisted?.order ?? String(cat.orderDefault ?? 2);
  return `
    <label class="field">
      <span>Order of accuracy p</span>
      <input name="order" type="number" min="${min}" max="${max}" step="1" value="${val}" required />
    </label>
    <p class="hint multistep-note">For multistep methods, startup values are generated by Runge-Kutta 4.</p>
  `;
}

function render(): void {
  const meta = selectedMeta();
  app.innerHTML = "";

  const shell = document.createElement("div");
  shell.className = "shell";

  const comparePicking = session.mode === "compare_pick";
  let lede = DEFAULT_LEDE;
  if (comparePicking && session.mode === "compare_pick") {
    lede =
      session.first === null
        ? "Choose the first first-order method, then a second method. You will enter one shared model y′ = f(t, y)."
        : `First method: ${methodLabel(session.first)}. Choose a different second method.`;
  }

  shell.innerHTML = `
    <header class="hero">
      <p class="eyebrow">AI-Assisted Educational Solver</p>
      <h1>Numerical ODE Lab</h1>
      <p class="lede">${lede}</p>
      <p class="ivp-note">First-order IVP: y′ = f(t, y), y(t₀) = y₀. Use JavaScript syntax with <code>t</code> and <code>y</code> (or <code>u</code> for Leap-Frog).</p>
      ${
        comparePickError
          ? `<p class="compare-error" role="alert">${comparePickError}</p>`
          : ""
      }
      <div class="steps" role="navigation" aria-label="Progress">
        <span class="pill ${step === "choose" ? "active" : ""}">1 · Method</span>
        <span class="arrow">→</span>
        <span class="pill ${step === "configure" ? "active" : ""}">2 · Data</span>
        <span class="arrow">→</span>
        <span class="pill ${step === "results" ? "active" : ""}">3 · Output</span>
      </div>
    </header>
  `;

  const main = document.createElement("main");
  main.className = "panel";

  if (step === "choose") {
    main.append(renderChoosePanel());
  } else if (step === "configure") {
    if (session.mode === "compare") {
      main.append(
        renderCompareForm(
          catalogEntry(session.a),
          catalogEntry(session.b),
          session.a,
          session.b
        )
      );
    } else if (meta && selected) {
      main.append(renderForm(meta, selected));
    } else {
      step = "choose";
      main.append(renderChoosePanel());
    }
  } else if (step === "results") {
    if (lastCompare) {
      main.append(
        renderCompareResultsShell(
          catalogEntry(lastCompare.a),
          catalogEntry(lastCompare.b),
          lastCompare.resultA,
          lastCompare.resultB
        )
      );
    } else if (meta && lastResult) {
      main.append(renderResultsShell(meta, lastResult));
    } else {
      step = "configure";
      main.append(renderChoosePanel());
    }
  } else {
    step = "choose";
    main.append(renderChoosePanel());
  }

  shell.append(main);
  app.append(shell);
}

function renderChoosePanel(): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "choose-panel";

  if (session.mode === "compare_pick") {
    const bar = document.createElement("div");
    bar.className = "choose-actions";
    bar.innerHTML = `<button type="button" class="btn ghost" data-cancel-compare>Cancel compare</button>`;
    bar.querySelector("[data-cancel-compare]")!.addEventListener("click", () => {
      session = { mode: "single" };
      comparePickError = "";
      render();
    });
    wrap.append(bar);
    wrap.append(renderCompareMethodGrid());
    return wrap;
  }

  const bar = document.createElement("div");
  bar.className = "choose-actions";
  bar.innerHTML = `
    <button type="button" class="btn secondary" data-compare>Compare two methods</button>
    <p class="compare-hint">One shared y′ = f(t, y) setup (first-order methods only).</p>
  `;
  bar.querySelector("[data-compare]")!.addEventListener("click", () => {
    session = { mode: "compare_pick", first: null };
    comparePickError = "";
    render();
  });
  wrap.append(bar);
  wrap.append(renderSingleMethodGrid());
  return wrap;
}

function renderMethodCard(
  cat: MethodCatalogEntry,
  onClick: () => void
): HTMLButtonElement {
  const card = document.createElement("button");
  card.type = "button";
  card.className = "card";
  const tag =
    cat.mode === "first"
      ? "First-order y′ = f(t, y)"
      : "Second-order u″ = a(t, u)";
  card.innerHTML = `
    <h2>${cat.displayName}</h2>
    <p>${cat.blurb}</p>
    <span class="tag">${tag}</span>
  `;
  card.addEventListener("click", onClick);
  return card;
}

function renderSingleMethodGrid(): HTMLElement {
  const grid = document.createElement("div");
  grid.className = "grid-methods";
  METHOD_CATALOG.forEach((cat) => {
    grid.append(
      renderMethodCard(cat, () => {
        session = { mode: "single" };
        selected = {
          family: cat.family,
          order: cat.orderDefault,
        };
        step = "configure";
        render();
      })
    );
  });
  return grid;
}

function renderCompareMethodGrid(): HTMLElement {
  const grid = document.createElement("div");
  grid.className = "grid-methods";
  FIRST_ORDER_CATALOG.forEach((cat) => {
    grid.append(
      renderMethodCard(cat, () => {
        if (session.mode !== "compare_pick") return;
        const pick: SelectedMethod = {
          family: cat.family,
          order: cat.orderDefault,
        };
        if (session.first === null) {
          comparePickError = "";
          session = { mode: "compare_pick", first: pick };
          render();
          return;
        }
        const sameConfig =
          session.first.family === pick.family &&
          (session.first.order ?? cat.orderDefault) ===
            (pick.order ?? cat.orderDefault);
        if (sameConfig) {
          comparePickError =
            "Pick a different method (or change order p in the next step).";
          render();
          return;
        }
        comparePickError = "";
        session = { mode: "compare", a: session.first, b: pick };
        step = "configure";
        render();
      })
    );
  });
  return grid;
}

function firstOrderInputDefaults() {
  const p = persisted;
  return {
    t0: p?.t0 ?? "0",
    tEnd: p?.tEnd ?? "5",
    h: p?.h ?? "0.05",
    y0: p?.y0 ?? "1",
    expr: p?.problemKind === "first" ? p.expr : "-y",
    order: p?.order ?? "2",
  };
}

function secondOrderInputDefaults() {
  const p = persisted;
  return {
    t0: p?.t0 ?? "0",
    tEnd: p?.tEnd ?? "5",
    h: p?.h ?? "0.05",
    u0: p?.u0 ?? "1",
    v0: p?.v0 ?? "0",
    expr: p?.problemKind === "second" ? p.expr : "-u",
  };
}

function renderForm(meta: MethodCatalogEntry, sel: SelectedMethod): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "form-wrap";
  const isSecond = meta.mode === "second";
  const fo = firstOrderInputDefaults();
  const so = secondOrderInputDefaults();
  const t0v = isSecond ? so.t0 : fo.t0;
  const tEndv = isSecond ? so.tEnd : fo.tEnd;
  const hv = isSecond ? so.h : fo.h;
  const title = methodLabel(sel);

  wrap.innerHTML = `
    <div class="form-head">
      <button type="button" class="btn ghost" data-back-methods>← All methods (keep my numbers)</button>
      <h2>${title}</h2>
    </div>
    <form class="form" id="ode-form">
      ${!isSecond ? orderFieldHtml(meta) : ""}
      <label class="field">
        <span>Start time t₀</span>
        <input name="t0" type="number" value="${t0v}" step="any" required />
      </label>
      <label class="field">
        <span>End time t_end</span>
        <input name="tEnd" type="number" value="${tEndv}" step="any" required />
      </label>
      <label class="field">
        <span>Step size h = Δt</span>
        <input name="h" type="number" value="${hv}" min="1e-9" step="any" required />
      </label>
      ${
        isSecond
          ? `
      <label class="field">
        <span>Initial position u₀</span>
        <input name="u0" type="number" value="${so.u0}" step="any" required />
      </label>
      <label class="field">
        <span>Initial velocity u′₀</span>
        <input name="v0" type="number" value="${so.v0}" step="any" required />
      </label>
      <label class="field wide">
        <span>u″ = a(t, u) — use <code>t</code> and <code>u</code></span>
        <input name="expr" type="text" value="" required placeholder="-u" />
      </label>
      `
          : `
      <label class="field">
        <span>Initial value y₀</span>
        <input name="y0" type="number" value="${fo.y0}" step="any" required />
      </label>
      <label class="field wide">
        <span>y′ = f(t, y) — use <code>t</code> and <code>y</code></span>
        <input name="expr" type="text" value="" required placeholder="-y" />
      </label>
      `
      }
      <p class="hint">Examples: <code>-y</code>, <code>t - y</code>, <code>Math.sin(t) - 0.1*y</code></p>
      <div class="actions">
        <button type="submit" class="btn primary">Run simulation</button>
      </div>
      <p class="error" id="form-error" hidden></p>
    </form>
  `;

  const exprEl = wrap.querySelector<HTMLInputElement>('input[name="expr"]');
  if (exprEl) exprEl.value = isSecond ? so.expr : fo.expr;

  wrap.querySelector("[data-back-methods]")!.addEventListener("click", () => {
    const form = wrap.querySelector<HTMLFormElement>("#ode-form");
    if (form) readPersistedFromFormEl(form);
    step = "choose";
    selected = null;
    lastResult = null;
    lastCompare = null;
    session = { mode: "single" };
    render();
  });

  wrap.querySelector("#ode-form")!.addEventListener("submit", (ev) => {
    ev.preventDefault();
    const form = ev.target as HTMLFormElement;
    const err = wrap.querySelector<HTMLParagraphElement>("#form-error")!;
    err.hidden = true;
    try {
      const fd = new FormData(form);
      const t0 = Number(fd.get("t0"));
      const tEnd = Number(fd.get("tEnd"));
      const h = Number(fd.get("h"));
      const expr = String(fd.get("expr") ?? "");

      let result: SolverResult;
      if (isSecond) {
        persistFromSecondOrderFd(fd);
        const u0 = Number(fd.get("u0"));
        const v0 = Number(fd.get("v0"));
        const a = compileScalarExpr(expr, "second");
        result = integrateSecondOrder({ t0, u0, v0, tEnd, h, a });
      } else {
        persistFromFirstOrderFd(fd);
        const y0 = Number(fd.get("y0"));
        const order = Number(fd.get("order"));
        sel.order = order;
        const f = compileScalarExpr(expr, "first");
        result = integrateFirstOrder(configFromSelection(sel), {
          t0,
          y0,
          tEnd,
          h,
          f,
        });
      }

      lastCompare = null;
      lastResult = result;
      lastProblemInputs = isSecond
        ? {
            kind: "second_order",
            equationDisplay: `u″ = a(t, u) with a(t, u) = ${expr}`,
            t0,
            tEnd,
            h,
            u0: Number(fd.get("u0")),
            v0: Number(fd.get("v0")),
          }
        : {
            kind: "first_order",
            equationDisplay: `y′ = f(t, y) with f(t, y) = ${expr}`,
            t0,
            tEnd,
            h,
            y0: Number(fd.get("y0")),
          };
      resetTutorConversation();
      step = "results";
      render();
    } catch (e) {
      err.textContent = e instanceof Error ? e.message : String(e);
      err.hidden = false;
    }
  });

  return wrap;
}

function renderCompareForm(
  metaA: MethodCatalogEntry,
  metaB: MethodCatalogEntry,
  selA: SelectedMethod,
  selB: SelectedMethod
): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "form-wrap";
  const fo = firstOrderInputDefaults();

  wrap.innerHTML = `
    <div class="form-head">
      <button type="button" class="btn ghost" data-back-methods>← Change method pair</button>
      <h2>Compare: ${methodLabel(selA)} vs ${methodLabel(selB)}</h2>
    </div>
    <p class="hint">Set order p for each multistep method before running (defaults from method cards).</p>
    <form class="form" id="ode-form">
      <label class="field">
        <span>Order p — ${metaA.displayName}</span>
        <input name="orderA" type="number" min="${metaA.orderMin ?? 1}" max="${metaA.orderMax ?? 8}" value="${selA.order ?? metaA.orderDefault ?? 2}" ${metaA.hasOrderSelector ? "required" : "disabled"} />
      </label>
      <label class="field">
        <span>Order p — ${metaB.displayName}</span>
        <input name="orderB" type="number" min="${metaB.orderMin ?? 1}" max="${metaB.orderMax ?? 8}" value="${selB.order ?? metaB.orderDefault ?? 2}" ${metaB.hasOrderSelector ? "required" : "disabled"} />
      </label>
      <label class="field">
        <span>Start time t₀</span>
        <input name="t0" type="number" value="${fo.t0}" step="any" required />
      </label>
      <label class="field">
        <span>End time t_end</span>
        <input name="tEnd" type="number" value="${fo.tEnd}" step="any" required />
      </label>
      <label class="field">
        <span>Step size h</span>
        <input name="h" type="number" value="${fo.h}" min="1e-9" step="any" required />
      </label>
      <label class="field">
        <span>Initial value y₀</span>
        <input name="y0" type="number" value="${fo.y0}" step="any" required />
      </label>
      <label class="field wide">
        <span>Shared y′ = f(t, y)</span>
        <input name="expr" type="text" value="" required placeholder="-y" />
      </label>
      <p class="hint multistep-note">For multistep methods, startup values are generated by Runge-Kutta 4.</p>
      <div class="actions">
        <button type="submit" class="btn primary">Run comparison</button>
      </div>
      <p class="error" id="form-error" hidden></p>
    </form>
  `;

  const exprCmp = wrap.querySelector<HTMLInputElement>('input[name="expr"]');
  if (exprCmp) exprCmp.value = fo.expr;

  wrap.querySelector("[data-back-methods]")!.addEventListener("click", () => {
    const form = wrap.querySelector<HTMLFormElement>("#ode-form");
    if (form) persistFromFirstOrderFd(new FormData(form));
    step = "choose";
    lastCompare = null;
    lastResult = null;
    session = { mode: "compare_pick", first: null };
    render();
  });

  wrap.querySelector("#ode-form")!.addEventListener("submit", (ev) => {
    ev.preventDefault();
    const form = ev.target as HTMLFormElement;
    const err = wrap.querySelector<HTMLParagraphElement>("#form-error")!;
    err.hidden = true;
    if (session.mode !== "compare") return;
    try {
      const fd = new FormData(form);
      persistFromFirstOrderFd(fd);
      const t0 = Number(fd.get("t0"));
      const tEnd = Number(fd.get("tEnd"));
      const h = Number(fd.get("h"));
      const expr = String(fd.get("expr") ?? "");
      const y0 = Number(fd.get("y0"));
      const f = compileScalarExpr(expr, "first");

      const a: SelectedMethod = {
        ...session.a,
        order: metaA.hasOrderSelector
          ? Number(fd.get("orderA"))
          : typeof metaA.orderOfAccuracy === "number"
            ? metaA.orderOfAccuracy
            : undefined,
      };
      const b: SelectedMethod = {
        ...session.b,
        order: metaB.hasOrderSelector
          ? Number(fd.get("orderB"))
          : typeof metaB.orderOfAccuracy === "number"
            ? metaB.orderOfAccuracy
            : undefined,
      };

      const base = { t0, y0, tEnd, h, f };
      const resultA = integrateFirstOrder(configFromSelection(a), base);
      const resultB = integrateFirstOrder(configFromSelection(b), base);
      lastResult = null;
      lastProblemInputs = null;
      lastCompare = { a, b, resultA, resultB };
      resetTutorConversation();
      step = "results";
      render();
    } catch (e) {
      err.textContent = e instanceof Error ? e.message : String(e);
      err.hidden = false;
    }
  });

  return wrap;
}

function goToMethodListKeepInputs(): void {
  step = "choose";
  selected = null;
  lastResult = null;
  lastCompare = null;
  session = { mode: "single" };
  render();
}

function metadataPanelHtml(meta: SolverResult["metadata"]): string {
  const coeffText = formatCoefficients(
    meta.coefficients?.alpha,
    meta.coefficients?.beta
  );
  const notesHtml = meta.notes
    .map((n) => `<li>${escapeHtml(n)}</li>`)
    .join("");
  return `
    <section class="edu-panel">
      <h3>Method details</h3>
      <dl class="meta-dl">
        <dt>Method</dt><dd>${escapeHtml(meta.displayName)}</dd>
        <dt>Order of accuracy p</dt><dd>${meta.order}</dd>
        <dt>Type</dt><dd>${meta.isImplicit ? "Implicit" : "Explicit"}</dd>
        ${
          meta.startupMethod
            ? `<dt>Startup</dt><dd>${escapeHtml(meta.startupMethod)}</dd>`
            : ""
        }
      </dl>
      <h4>Formula</h4>
      <div class="formula-block">${escapeHtml(meta.formulaDisplay)}</div>
      ${
        coeffText
          ? `<h4>Coefficients</h4><div class="formula-inline">${escapeHtml(coeffText)}</div>`
          : ""
      }
      ${
        notesHtml
          ? `<h4>Notes</h4><ul class="edu-notes">${notesHtml}</ul>`
          : ""
      }
    </section>
  `;
}

function renderResultsShell(
  meta: MethodCatalogEntry,
  result: SolverResult
): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "results-wrap";
  wrap.innerHTML = `
    <div class="form-head">
      <button type="button" class="btn ghost" data-back>← Edit inputs</button>
      <button type="button" class="btn ghost" data-methods>All methods (keep my numbers)</button>
    </div>
    <div class="results-layout">
      <div class="results-main" id="results-body"></div>
      <div id="ai-tutor-host"></div>
    </div>
  `;
  wrap.querySelector("[data-back]")!.addEventListener("click", () => {
    step = "configure";
    render();
  });
  wrap.querySelector("[data-methods]")!.addEventListener("click", () => {
    goToMethodListKeepInputs();
  });
  queueMicrotask(() => {
    mountResults(meta, result);
    const tutorHost = wrap.querySelector<HTMLDivElement>("#ai-tutor-host");
    if (tutorHost) {
      mountAiTutorPanel(tutorHost, {
        enabled: true,
        result,
        meta,
        problem: lastProblemInputs,
        getChart: () => chart,
      });
    }
  });
  return wrap;
}

function renderCompareResultsShell(
  metaA: MethodCatalogEntry,
  metaB: MethodCatalogEntry,
  resultA: SolverResult,
  resultB: SolverResult
): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = "results-wrap";
  wrap.innerHTML = `
    <div class="form-head">
      <button type="button" class="btn ghost" data-back>← Edit inputs</button>
      <button type="button" class="btn ghost" data-pair>Change method pair</button>
      <button type="button" class="btn ghost" data-methods>All methods (keep my numbers)</button>
    </div>
    <div class="results-layout">
      <div class="results-main" id="results-body"></div>
      <div id="ai-tutor-host"></div>
    </div>
  `;
  wrap.querySelector("[data-back]")!.addEventListener("click", () => {
    step = "configure";
    render();
  });
  wrap.querySelector("[data-pair]")!.addEventListener("click", () => {
    step = "choose";
    lastCompare = null;
    lastResult = null;
    session = { mode: "compare_pick", first: null };
    render();
  });
  wrap.querySelector("[data-methods]")!.addEventListener("click", () => {
    goToMethodListKeepInputs();
  });
  queueMicrotask(() => {
    mountCompareResults(metaA, metaB, resultA, resultB);
    const tutorHost = wrap.querySelector<HTMLDivElement>("#ai-tutor-host");
    if (tutorHost) {
      mountAiTutorPanel(tutorHost, {
        enabled: false,
        result: null,
        meta: null,
        problem: null,
        getChart: () => chart,
      });
    }
  });
  return wrap;
}

function mountResults(
  meta: MethodCatalogEntry,
  result: SolverResult
): void {
  const body = document.querySelector("#results-body");
  if (!body) return;

  const series = result.points;
  const last = series[series.length - 1]!;
  const valueLabel = meta.mode === "second" ? "u" : "y";

  body.innerHTML = `
    <section class="summary">
      <h2>${result.metadata.displayName} · results</h2>
      <div class="stat-grid">
        <div class="stat">
          <span class="stat-label">Steps taken</span>
          <span class="stat-value">${series.length}</span>
        </div>
        <div class="stat">
          <span class="stat-label">Final time</span>
          <span class="stat-value">${last.t.toFixed(6)}</span>
        </div>
        <div class="stat">
          <span class="stat-label">Final ${valueLabel}</span>
          <span class="stat-value">${last.y.toFixed(8)}</span>
        </div>
        ${
          meta.mode === "second" && last.v !== undefined
            ? `<div class="stat"><span class="stat-label">Final u′</span><span class="stat-value">${last.v.toFixed(8)}</span></div>`
            : ""
        }
      </div>
    </section>
    ${metadataPanelHtml(result.metadata)}
    <section class="chart-section">
      <canvas id="plot" height="120"></canvas>
    </section>
    <section class="table-section">
      <h3>Last 12 values</h3>
      <div class="table-scroll">
        <table>
          <thead>
            <tr><th>t</th><th>${valueLabel}</th>${meta.mode === "second" ? "<th>u′</th>" : ""}</tr>
          </thead>
          <tbody>
            ${series
              .slice(-12)
              .map(
                (p) =>
                  `<tr><td>${p.t.toFixed(5)}</td><td>${p.y.toFixed(8)}</td>${
                    meta.mode === "second"
                      ? `<td>${p.v?.toFixed(8) ?? ""}</td>`
                      : ""
                  }</tr>`
              )
              .join("")}
          </tbody>
        </table>
      </div>
    </section>
  `;

  drawSingleChart(meta, series);
}

function drawSingleChart(
  meta: MethodCatalogEntry,
  series: SeriesPoint[]
): void {
  const canvas = document.querySelector<HTMLCanvasElement>("#plot");
  if (!canvas) return;
  chart?.destroy();
  const ts = series.map((p) => p.t.toFixed(3));
  const ys = series.map((p) => p.y);
  const valueLabel = meta.mode === "second" ? "u" : "y";

  const datasets =
    meta.mode === "second" && series.some((p) => p.v !== undefined)
      ? [
          {
            label: "u(t)",
            data: ys,
            borderColor: "#5b8cff",
            tension: 0.15,
            fill: false,
            pointRadius: 0,
          },
          {
            label: "u′(t)",
            data: series.map((p) => p.v ?? NaN),
            borderColor: "#7ae2a8",
            tension: 0.15,
            fill: false,
            pointRadius: 0,
          },
        ]
      : [
          {
            label: `${valueLabel}(t)`,
            data: ys,
            borderColor: "#5b8cff",
            backgroundColor: "rgba(91, 140, 255, 0.12)",
            tension: 0.15,
            fill: true,
            pointRadius: 0,
          },
        ];

  chart = new Chart(canvas, {
    type: "line",
    data: { labels: ts, datasets },
    options: chartOptions(series, meta.mode === "second" ? "u , u′" : valueLabel),
  });
}

function chartOptions(
  series: SeriesPoint[],
  yTitle: string
): object {
  return {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: "index", intersect: false },
    plugins: {
      legend: { labels: { color: "#d8e2ff" } },
      title: {
        display: true,
        text: "Approximate solution vs time",
        color: "#f2f5ff",
        font: { size: 16, weight: "600" },
      },
      tooltip: {
        callbacks: {
          title: (items: { dataIndex?: number }[]) => {
            const i = items[0]?.dataIndex ?? 0;
            return `t = ${series[i]?.t.toFixed(6)}`;
          },
        },
      },
    },
    scales: {
      x: {
        title: { display: true, text: "t", color: "#9fb2df" },
        ticks: { color: "#9fb2df", maxTicksLimit: 8 },
        grid: { color: "rgba(255, 255, 255, 0.06)" },
      },
      y: {
        title: { display: true, text: yTitle, color: "#9fb2df" },
        ticks: { color: "#9fb2df" },
        grid: { color: "rgba(255, 255, 255, 0.06)" },
      },
    },
  };
}

function mountCompareResults(
  _metaA: MethodCatalogEntry,
  _metaB: MethodCatalogEntry,
  resultA: SolverResult,
  resultB: SolverResult
): void {
  const body = document.querySelector("#results-body");
  if (!body) return;

  const seriesA = resultA.points;
  const seriesB = resultB.points;
  const la = seriesA[seriesA.length - 1]!;
  const lb = seriesB[seriesB.length - 1]!;
  const diff = Math.abs(la.y - lb.y);

  if (seriesA.length !== seriesB.length) {
    body.innerHTML =
      '<p class="compare-error">Series length mismatch; plots may be unreliable.</p>';
    return;
  }

  body.innerHTML = `
    <section class="summary">
      <h2>Comparison · ${resultA.metadata.displayName} vs ${resultB.metadata.displayName}</h2>
      <div class="stat-grid">
        <div class="stat"><span class="stat-label">Steps (each)</span><span class="stat-value">${seriesA.length}</span></div>
        <div class="stat"><span class="stat-label">Final time</span><span class="stat-value">${la.t.toFixed(6)}</span></div>
        <div class="stat"><span class="stat-label">Final y — ${escapeHtml(resultA.metadata.displayName)}</span><span class="stat-value">${la.y.toFixed(8)}</span></div>
        <div class="stat"><span class="stat-label">Final y — ${escapeHtml(resultB.metadata.displayName)}</span><span class="stat-value">${lb.y.toFixed(8)}</span></div>
        <div class="stat"><span class="stat-label">|uₙ − yₙ| at final t</span><span class="stat-value">${diff.toExponential(4)}</span></div>
      </div>
    </section>
    <div class="compare-meta-grid">
      ${metadataPanelHtml(resultA.metadata)}
      ${metadataPanelHtml(resultB.metadata)}
    </div>
    <section class="chart-section">
      <canvas id="plot" height="120"></canvas>
    </section>
    <section class="table-section">
      <h3>Last 12 steps (both methods)</h3>
      <div class="table-scroll">
        <table>
          <thead>
            <tr>
              <th>t</th>
              <th>y — ${escapeHtml(resultA.metadata.displayName)}</th>
              <th>y — ${escapeHtml(resultB.metadata.displayName)}</th>
              <th>|Δy|</th>
            </tr>
          </thead>
          <tbody>
            ${(() => {
              const tailA = seriesA.slice(-12);
              const off = seriesA.length - tailA.length;
              return tailA
                .map((pa, idx) => {
                  const pb = seriesB[off + idx]!;
                  return `<tr><td>${pa.t.toFixed(5)}</td><td>${pa.y.toFixed(8)}</td><td>${pb.y.toFixed(8)}</td><td>${Math.abs(pa.y - pb.y).toExponential(4)}</td></tr>`;
                })
                .join("");
            })()}
          </tbody>
        </table>
      </div>
    </section>
  `;

  const canvas = document.querySelector<HTMLCanvasElement>("#plot");
  if (!canvas) return;
  chart?.destroy();
  chart = new Chart(canvas, {
    type: "line",
    data: {
      labels: seriesA.map((p) => p.t.toFixed(3)),
      datasets: [
        {
          label: resultA.metadata.displayName,
          data: seriesA.map((p) => p.y),
          borderColor: "#5b8cff",
          tension: 0.15,
          pointRadius: 0,
        },
        {
          label: resultB.metadata.displayName,
          data: seriesB.map((p) => p.y),
          borderColor: "#ffb86b",
          tension: 0.15,
          pointRadius: 0,
        },
      ],
    },
    options: chartOptions(seriesA, "y"),
  });
}

render();
